### ISSUE TITLE
steamcmd fails to install to specified dir

### ISSUE THREAD

**Issue by drouo** [abnormalend/valheim-terraform#11]
steamcmd fails to install to specified dir, putting valheim in /home/ubuntu/... we found it via sudo find / valheim

**Comment by abnormalend** [comment]
This is resolved, it installs to the given directory when we install with:
`/usr/games/steamcmd +@sSteamCmdForcePlatformType linux \
                    +force_install_dir $valheim_dir \
                    +login anonymous \
                    +app_update 896660 \
                    -beta none validate \
                    +quit`
